name: project_mobile

publish_to: none

environment:
  sdk: ^3.0.0

dev_dependencies:
  melos: ^6.0.0
dependencies:
  sqflite: ^2.4.2+1
  path: ^1.9.1
  path_provider: ^2.1.5
  connectivity_plus: ^7.1.1
